repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.1
    hooks:
      - id: ruff
        args: [--fix]
        exclude: ^tests/
      - id: ruff-format
        exclude: ^tests/

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        additional_dependencies: [tomli]
        args: [src]

  - repo: https://github.com/DetachHead/basedpyright-pre-commit-mirror
    rev: 1.38.0
    hooks:
      - id: basedpyright
        args: [--level, error]
        exclude: ^tests/
